# Generated by Django 4.2.5 on 2023-09-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.TextField(default='without title')),
                ('text', models.TextField(default='without text')),
                ('shared_file', models.FileField(blank=True, upload_to='FileSharer/static/files/')),
            ],
        ),
    ]
